# Parameterize Location to the test resources deployment script. This allows
# specifying a different Azure region to use when manually triggering the live
# tests pipeline. This is useful for when we want to test in different
# environments: Prod, Canary, etc.
parameters:
- name: location
  displayName: Location
  type: string
  default: westcentralus

trigger: none
resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

jobs:
  - template: ../../../eng/pipelines/templates/jobs/archetype-sdk-integration.yml
    parameters:
      PackageName: "@azure/ai-form-recognizer"
      ResourceServiceDirectory: formrecognizer
      Location: "${{ parameters.Location }}"
      TestSamples: false
      EnvVars:
        AZURE_CLIENT_ID: $(aad-azure-sdk-test-client-id)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
        AZURE_CLIENT_SECRET: $(aad-azure-sdk-test-client-secret)
